dist: trusty
sudo: required
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libgl1-mesa-dev
#before_install:
#  - sudo apt-get install libsfml-dev
script:
  - gcc -v
  - export CC=gcc-8
  - export CXX=g++-8
  - cmake --target unittests .
  - make -j 4
  - ./build/unittests