name: Linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install pythonpy clang-format-10 clang-tidy-10
        mkdir output

    - name: clang-format
      shell: bash
      run: |
        python3 .github/check-linting.py -r --exclude fluffy/contrib --exclude fluffy/platform fluffy >> "output/lint-fluffy-${{ github.run_id }}.diff"
        python3 .github/check-linting.py -r --exclude fluffy/contrib --exclude fluffy/platform sandbox >> "output/lint-sandbox-${{ github.run_id }}.diff"
        python3 .github/check-linting.py -r --exclude fluffy/contrib --exclude fluffy/platform editor >> "output/lint-editor-${{ github.run_id }}.diff"

    - name: Archive diff
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: clang-format-diff
        path: "output/"